#!/bin/sh
set -eu

base_url="https://beadpattern.net"
command="${1:-home}"
value="${2:-}"

case "$command" in
  home)
    printf '%s\n' "$base_url"
    ;;
  tool)
    clean=$(printf '%s' "$value" | sed 's#^/*##; s#/*$##')
    if [ -z "$clean" ]; then
      printf '%s\n' "$base_url"
    else
      printf '%s/%s\n' "$base_url" "$clean"
    fi
    ;;
  search)
    query=$(printf '%s' "$value" | sed 's/ /+/g')
    printf '%s/search?q=%s\n' "$base_url" "$query"
    ;;
  *)
    printf 'usage: beadpattern-site-kit [home|tool <slug>|search <query>]\n' >&2
    exit 64
    ;;
esac
